/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as OutRouteImport } from './routes/out'
import { Route as NewRouteImport } from './routes/new'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DrinksRouteImport } from './routes/drinks'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PantryIndexRouteImport } from './routes/pantry.index'
import { Route as OutIndexRouteImport } from './routes/out.index'
import { Route as DrinksIndexRouteImport } from './routes/drinks.index'
import { Route as CookbookIndexRouteImport } from './routes/cookbook.index'
import { Route as PantryIdRouteImport } from './routes/pantry.$id'
import { Route as OutIdRouteImport } from './routes/out.$id'
import { Route as DrinksIdRouteImport } from './routes/drinks.$id'
import { Route as CookbookIdRouteImport } from './routes/cookbook.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const OutRoute = OutRouteImport.update({
  id: '/out',
  path: '/out',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksRoute = DrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryIndexRoute = PantryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PantryRoute,
} as any)
const OutIndexRoute = OutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutRoute,
} as any)
const DrinksIndexRoute = DrinksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrinksRoute,
} as any)
const CookbookIndexRoute = CookbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CookbookRoute,
} as any)
const PantryIdRoute = PantryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PantryRoute,
} as any)
const OutIdRoute = OutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OutRoute,
} as any)
const DrinksIdRoute = DrinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DrinksRoute,
} as any)
const CookbookIdRoute = CookbookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CookbookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/drinks': typeof DrinksRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/new': typeof NewRoute
  '/out': typeof OutRouteWithChildren
  '/pantry': typeof PantryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/cookbook/$id': typeof CookbookIdRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/out/$id': typeof OutIdRoute
  '/pantry/$id': typeof PantryIdRoute
  '/cookbook/': typeof CookbookIndexRoute
  '/drinks/': typeof DrinksIndexRoute
  '/out/': typeof OutIndexRoute
  '/pantry/': typeof PantryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/new': typeof NewRoute
  '/settings': typeof SettingsRoute
  '/cookbook/$id': typeof CookbookIdRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/out/$id': typeof OutIdRoute
  '/pantry/$id': typeof PantryIdRoute
  '/cookbook': typeof CookbookIndexRoute
  '/drinks': typeof DrinksIndexRoute
  '/out': typeof OutIndexRoute
  '/pantry': typeof PantryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/drinks': typeof DrinksRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/new': typeof NewRoute
  '/out': typeof OutRouteWithChildren
  '/pantry': typeof PantryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/cookbook/$id': typeof CookbookIdRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/out/$id': typeof OutIdRoute
  '/pantry/$id': typeof PantryIdRoute
  '/cookbook/': typeof CookbookIndexRoute
  '/drinks/': typeof DrinksIndexRoute
  '/out/': typeof OutIndexRoute
  '/pantry/': typeof PantryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookbook'
    | '/drinks'
    | '/favorites'
    | '/new'
    | '/out'
    | '/pantry'
    | '/settings'
    | '/cookbook/$id'
    | '/drinks/$id'
    | '/out/$id'
    | '/pantry/$id'
    | '/cookbook/'
    | '/drinks/'
    | '/out/'
    | '/pantry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/new'
    | '/settings'
    | '/cookbook/$id'
    | '/drinks/$id'
    | '/out/$id'
    | '/pantry/$id'
    | '/cookbook'
    | '/drinks'
    | '/out'
    | '/pantry'
  id:
    | '__root__'
    | '/'
    | '/cookbook'
    | '/drinks'
    | '/favorites'
    | '/new'
    | '/out'
    | '/pantry'
    | '/settings'
    | '/cookbook/$id'
    | '/drinks/$id'
    | '/out/$id'
    | '/pantry/$id'
    | '/cookbook/'
    | '/drinks/'
    | '/out/'
    | '/pantry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRoute: typeof CookbookRouteWithChildren
  DrinksRoute: typeof DrinksRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  NewRoute: typeof NewRoute
  OutRoute: typeof OutRouteWithChildren
  PantryRoute: typeof PantryRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/out': {
      id: '/out'
      path: '/out'
      fullPath: '/out'
      preLoaderRoute: typeof OutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry/': {
      id: '/pantry/'
      path: '/'
      fullPath: '/pantry/'
      preLoaderRoute: typeof PantryIndexRouteImport
      parentRoute: typeof PantryRoute
    }
    '/out/': {
      id: '/out/'
      path: '/'
      fullPath: '/out/'
      preLoaderRoute: typeof OutIndexRouteImport
      parentRoute: typeof OutRoute
    }
    '/drinks/': {
      id: '/drinks/'
      path: '/'
      fullPath: '/drinks/'
      preLoaderRoute: typeof DrinksIndexRouteImport
      parentRoute: typeof DrinksRoute
    }
    '/cookbook/': {
      id: '/cookbook/'
      path: '/'
      fullPath: '/cookbook/'
      preLoaderRoute: typeof CookbookIndexRouteImport
      parentRoute: typeof CookbookRoute
    }
    '/pantry/$id': {
      id: '/pantry/$id'
      path: '/$id'
      fullPath: '/pantry/$id'
      preLoaderRoute: typeof PantryIdRouteImport
      parentRoute: typeof PantryRoute
    }
    '/out/$id': {
      id: '/out/$id'
      path: '/$id'
      fullPath: '/out/$id'
      preLoaderRoute: typeof OutIdRouteImport
      parentRoute: typeof OutRoute
    }
    '/drinks/$id': {
      id: '/drinks/$id'
      path: '/$id'
      fullPath: '/drinks/$id'
      preLoaderRoute: typeof DrinksIdRouteImport
      parentRoute: typeof DrinksRoute
    }
    '/cookbook/$id': {
      id: '/cookbook/$id'
      path: '/$id'
      fullPath: '/cookbook/$id'
      preLoaderRoute: typeof CookbookIdRouteImport
      parentRoute: typeof CookbookRoute
    }
  }
}

interface CookbookRouteChildren {
  CookbookIdRoute: typeof CookbookIdRoute
  CookbookIndexRoute: typeof CookbookIndexRoute
}

const CookbookRouteChildren: CookbookRouteChildren = {
  CookbookIdRoute: CookbookIdRoute,
  CookbookIndexRoute: CookbookIndexRoute,
}

const CookbookRouteWithChildren = CookbookRoute._addFileChildren(
  CookbookRouteChildren,
)

interface DrinksRouteChildren {
  DrinksIdRoute: typeof DrinksIdRoute
  DrinksIndexRoute: typeof DrinksIndexRoute
}

const DrinksRouteChildren: DrinksRouteChildren = {
  DrinksIdRoute: DrinksIdRoute,
  DrinksIndexRoute: DrinksIndexRoute,
}

const DrinksRouteWithChildren =
  DrinksRoute._addFileChildren(DrinksRouteChildren)

interface OutRouteChildren {
  OutIdRoute: typeof OutIdRoute
  OutIndexRoute: typeof OutIndexRoute
}

const OutRouteChildren: OutRouteChildren = {
  OutIdRoute: OutIdRoute,
  OutIndexRoute: OutIndexRoute,
}

const OutRouteWithChildren = OutRoute._addFileChildren(OutRouteChildren)

interface PantryRouteChildren {
  PantryIdRoute: typeof PantryIdRoute
  PantryIndexRoute: typeof PantryIndexRoute
}

const PantryRouteChildren: PantryRouteChildren = {
  PantryIdRoute: PantryIdRoute,
  PantryIndexRoute: PantryIndexRoute,
}

const PantryRouteWithChildren =
  PantryRoute._addFileChildren(PantryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRoute: CookbookRouteWithChildren,
  DrinksRoute: DrinksRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  NewRoute: NewRoute,
  OutRoute: OutRouteWithChildren,
  PantryRoute: PantryRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
