/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutRouteImport } from './routes/out'
import { Route as NewRouteImport } from './routes/new'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DrinksRouteImport } from './routes/drinks'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutIdRouteImport } from './routes/out.$id'
import { Route as DrinksIdRouteImport } from './routes/drinks.$id'
import { Route as CookbookIdRouteImport } from './routes/cookbook.$id'

const OutRoute = OutRouteImport.update({
  id: '/out',
  path: '/out',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinksRoute = DrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutIdRoute = OutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OutRoute,
} as any)
const DrinksIdRoute = DrinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DrinksRoute,
} as any)
const CookbookIdRoute = CookbookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CookbookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/drinks': typeof DrinksRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/new': typeof NewRoute
  '/out': typeof OutRouteWithChildren
  '/cookbook/$id': typeof CookbookIdRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/out/$id': typeof OutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/drinks': typeof DrinksRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/new': typeof NewRoute
  '/out': typeof OutRouteWithChildren
  '/cookbook/$id': typeof CookbookIdRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/out/$id': typeof OutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRouteWithChildren
  '/drinks': typeof DrinksRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/new': typeof NewRoute
  '/out': typeof OutRouteWithChildren
  '/cookbook/$id': typeof CookbookIdRoute
  '/drinks/$id': typeof DrinksIdRoute
  '/out/$id': typeof OutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookbook'
    | '/drinks'
    | '/favorites'
    | '/new'
    | '/out'
    | '/cookbook/$id'
    | '/drinks/$id'
    | '/out/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookbook'
    | '/drinks'
    | '/favorites'
    | '/new'
    | '/out'
    | '/cookbook/$id'
    | '/drinks/$id'
    | '/out/$id'
  id:
    | '__root__'
    | '/'
    | '/cookbook'
    | '/drinks'
    | '/favorites'
    | '/new'
    | '/out'
    | '/cookbook/$id'
    | '/drinks/$id'
    | '/out/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRoute: typeof CookbookRouteWithChildren
  DrinksRoute: typeof DrinksRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  NewRoute: typeof NewRoute
  OutRoute: typeof OutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/out': {
      id: '/out'
      path: '/out'
      fullPath: '/out'
      preLoaderRoute: typeof OutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drinks': {
      id: '/drinks'
      path: '/drinks'
      fullPath: '/drinks'
      preLoaderRoute: typeof DrinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/out/$id': {
      id: '/out/$id'
      path: '/$id'
      fullPath: '/out/$id'
      preLoaderRoute: typeof OutIdRouteImport
      parentRoute: typeof OutRoute
    }
    '/drinks/$id': {
      id: '/drinks/$id'
      path: '/$id'
      fullPath: '/drinks/$id'
      preLoaderRoute: typeof DrinksIdRouteImport
      parentRoute: typeof DrinksRoute
    }
    '/cookbook/$id': {
      id: '/cookbook/$id'
      path: '/$id'
      fullPath: '/cookbook/$id'
      preLoaderRoute: typeof CookbookIdRouteImport
      parentRoute: typeof CookbookRoute
    }
  }
}

interface CookbookRouteChildren {
  CookbookIdRoute: typeof CookbookIdRoute
}

const CookbookRouteChildren: CookbookRouteChildren = {
  CookbookIdRoute: CookbookIdRoute,
}

const CookbookRouteWithChildren = CookbookRoute._addFileChildren(
  CookbookRouteChildren,
)

interface DrinksRouteChildren {
  DrinksIdRoute: typeof DrinksIdRoute
}

const DrinksRouteChildren: DrinksRouteChildren = {
  DrinksIdRoute: DrinksIdRoute,
}

const DrinksRouteWithChildren =
  DrinksRoute._addFileChildren(DrinksRouteChildren)

interface OutRouteChildren {
  OutIdRoute: typeof OutIdRoute
}

const OutRouteChildren: OutRouteChildren = {
  OutIdRoute: OutIdRoute,
}

const OutRouteWithChildren = OutRoute._addFileChildren(OutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRoute: CookbookRouteWithChildren,
  DrinksRoute: DrinksRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  NewRoute: NewRoute,
  OutRoute: OutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
